version: "3.8"
services:
  itemcatalogue.api:
    image: itemcatalogueapi:1.0
    build:
      context: .
      dockerfile: ./src/ItemCatalogue.Api/Dockerfile
    ports:
      - "5125:5125"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - itemcataloguenet

networks:
  itemcataloguenet:
    driver: bridge
