version: "3.8"
services:
  itemcatalogue.api:
    image: itemcatalogue.api:1.0
    build:
      context: .
      dockerfile: ./src/ItemCatalogue.Api/Dockerfile
    ports:
      - "5125:5125"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - itemcataloguenet

  itemcatalogue.spa.angular.server:
    image: itemcatalogue.spa.angular.server:1.0
    build:
      context: .
      dockerfile: ./src/ItemCatalogue.Spa.Angular/ItemCatalogue.Spa.Angular.Server/Dockerfile
    ports:
      - "5000:5000" # Change this to the port your Angular server is running on
    networks:
      - itemcataloguenet

networks:
  itemcataloguenet:
    driver: bridge
